spring:
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/Herencia
    password: 123456Aa
    driverClassName: org.postgresql.Driver
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

#  jpa:
#    hibernate: ddl-auto=update
#    generate-ddl: true
#    database-platform: org.hibernate.dialect.PostgreSQL94Dialect

server:
  port: '8080'